
version: '3.8'

services:

  
  redis:
    
    image: "redis:alpine"
    
    command: redis-server --requirepass ${REDIS_PASSWORD}
    
    container_name: inferserve_redis


  api:
    
    build: .
    
    container_name: inferserve_api
    
    ports:
      - "8000:8000"
   
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    
    depends_on:
      - redis