


name: Python CI


on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


jobs:
  build:
    
    runs-on: ubuntu-latest

    
    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v3

    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip' 

    
    - name: Install dependencies
      run: |
        pip install -r requirements/requirements.txt
        pip install -r requirements/requirements-dev.txt

    
    - name: Run tests with pytest
      run: |
        pytest